force-app/main/default/objects/AE_Individual_Event__c/AE_Individual_Event__c.object-meta.xml
<CustomObject>
    <label>AE Individual Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AE Individual Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AE_Individual_Event__c/fields/AE_End_Date__c.field-meta.xml
<CustomField>
    <fullName>AE_End_Date__c</fullName>
    <label>AE End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AE_Individual_Event__c/fields/AE_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>AE_Start_Date__c</fullName>
    <label>AE Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AE_Individual_Event__c/fields/New_Potential_Adverse_Event__c.field-meta.xml
<CustomField>
    <fullName>New_Potential_Adverse_Event__c</fullName>
    <label>New Potential Adverse Event</label>
    <referenceTo>New_Potential_Adverse_Event__c</referenceTo>
    <relationshipLabel>AE Individual Events</relationshipLabel>
    <relationshipName>AE_Individual_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AE_Individual_Event__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Recovered</fullName>
            </value>
            <value>
                <fullName>Not Recovered</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AE_Product__c/fields/Dose__c.field-meta.xml
<CustomField>
    <fullName>Dose__c</fullName>
    <label>Dose</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AE_Product__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AE_Product__c/fields/Is_this_a_technical_complaint__c.field-meta.xml
<CustomField>
    <fullName>Is_this_a_technical_complaint__c</fullName>
    <label>Is this a technical complaint?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AE_Product__c/fields/Lot_Number__c.field-meta.xml
<CustomField>
    <fullName>Lot_Number__c</fullName>
    <label>Lot Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AE_Product__c/fields/New_Potential_Adverse_Event__c.field-meta.xml
<CustomField>
    <fullName>New_Potential_Adverse_Event__c</fullName>
    <label>New Potential Adverse Event</label>
    <referenceTo>New_Potential_Adverse_Event__c</referenceTo>
    <relationshipLabel>AE Products</relationshipLabel>
    <relationshipName>AE_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AE_Product__c/fields/Product_pickup_availability_status_is__c.field-meta.xml
<CustomField>
    <fullName>Product_pickup_availability_status_is__c</fullName>
    <label>Product pickup availability status is</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AE_Product__c/fields/Route_of_administering__c.field-meta.xml
<CustomField>
    <fullName>Route_of_administering__c</fullName>
    <label>Route of administering</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AE_Product__c/fields/Technical_complaint__c.field-meta.xml
<CustomField>
    <fullName>Technical_complaint__c</fullName>
    <label>Technical complaint</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AE_Product__c/fields/Therapy_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Therapy_End_Date__c</fullName>
    <label>Therapy End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AE_Product__c/fields/Therapy_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Therapy_Start_Date__c</fullName>
    <label>Therapy Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MICC_Product__c/MICC_Product__c.object-meta.xml
<CustomObject>
    <label>MICC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MICC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MICC_Product__c/fields/Product_Indication_Medicus__c.field-meta.xml
<CustomField>
    <fullName>Product_Indication_Medicus__c</fullName>
    <label>Product Indication</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Indication 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MICC_Product__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
            </value>
            <value>
                <fullName>OTC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/New_Potential_Adverse_Event__c.object-meta.xml
<CustomObject>
    <description>Main object to store Adverse Event cases.</description>
    <label>New Potential Adverse Event</label>
    <nameField>
        <displayFormat>AE-{0000}</displayFormat>
        <label>AE Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New Potential Adverse Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/AE_End_Date__c.field-meta.xml
<CustomField>
    <fullName>AE_End_Date__c</fullName>
    <label>AE End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/AE_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>AE_Start_Date__c</fullName>
    <label>AE Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/Congenital_Anomaly__c.field-meta.xml
<CustomField>
    <fullName>Congenital_Anomaly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Congenital Anomaly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/Death__c.field-meta.xml
<CustomField>
    <fullName>Death__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Death</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/Dose__c.field-meta.xml
<CustomField>
    <fullName>Dose__c</fullName>
    <label>Dose</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/Hospitalization__c.field-meta.xml
<CustomField>
    <fullName>Hospitalization__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hospitalization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/Is_Technical_Complaint__c.field-meta.xml
<CustomField>
    <fullName>Is_Technical_Complaint__c</fullName>
    <label>Is Technical Complaint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/Life_Threatening__c.field-meta.xml
<CustomField>
    <fullName>Life_Threatening__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Life Threatening</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/MICC_Product_Link__c.field-meta.xml
<CustomField>
    <fullName>MICC_Product_Link__c</fullName>
    <label>MICC Product</label>
    <referenceTo>MICC_Product__c</referenceTo>
    <relationshipLabel>New Potential Adverse Events</relationshipLabel>
    <relationshipName>New_Potential_Adverse_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/Other_Seriousness__c.field-meta.xml
<CustomField>
    <fullName>Other_Seriousness__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Other Seriousness</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/Pickup_Status__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Status__c</fullName>
    <label>Pickup Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/Product_Indication__c.field-meta.xml
<CustomField>
    <fullName>Product_Indication__c</fullName>
    <label>Product Indication</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/Relevant_Medical_History__c.field-meta.xml
<CustomField>
    <fullName>Relevant_Medical_History__c</fullName>
    <label>Relevant Medical History</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/Route_of_administering__c.field-meta.xml
<CustomField>
    <fullName>Route_of_administering__c</fullName>
    <label>Route of administering</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/Technical_Complaint_Desc__c.field-meta.xml
<CustomField>
    <fullName>Technical_Complaint_Desc__c</fullName>
    <label>Technical Complaint Desc</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/Technical_Complaint_Number__c.field-meta.xml
<CustomField>
    <fullName>Technical_Complaint_Number__c</fullName>
    <label>Technical Complaint Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/Therapy_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Therapy_End_Date__c</fullName>
    <label>Therapy End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/New_Potential_Adverse_Event__c/fields/Therapy_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Therapy_Start_Date__c</fullName>
    <label>Therapy Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ProductInfoController.cls
public with sharing class ProductInfoController {
    public New_Potential_Adverse_Event__c mainAE {get; set;}
    public List<ProductRow> rows {get; set;}
    public List<AERow> aeRows {get; set;}
    
    public Boolean seriousnessDeath {get; set;}
    public Boolean seriousnessLifeThreatening {get; set;}
    public Boolean seriousnessDisability {get; set;}
    public Boolean seriousnessHospitalization {get; set;}
    public Boolean seriousnessCongenitalAnomaly {get; set;}
    public Boolean seriousnessOther {get; set;}
    public String eventDescription {get; set;}
    public String relevantMedicalHistory {get; set;}
    public Boolean addIndividualEventsFlag {get; set;}

    public ProductInfoController() {
        mainAE = new New_Potential_Adverse_Event__c();
        rows = new List<ProductRow>{ new ProductRow(1) };
        aeRows = new List<AERow>{ new AERow(1) };
        
        // Map from Case if ID is present
        String caseId = ApexPages.currentPage().getParameters().get('caseId');
        if (String.isNotBlank(caseId)) {
            try {
                // Fetching Product_Indication__c from Case as requested
                String query = 'SELECT Product_Indication__c FROM Case WHERE Id = :caseId LIMIT 1';
                List<SObject> caseRecords = Database.query(query);
                if (!caseRecords.isEmpty() && caseRecords[0].get('Product_Indication__c') != null) {
                    rows[0].indication = (String)caseRecords[0].get('Product_Indication__c');
                }
            } catch (Exception e) { System.debug('Case fetch failed: ' + e.getMessage()); }
        }
    }

    public void fetchProductDetails() {
        try {
            String rowIdxStr = ApexPages.currentPage().getParameters().get('rowIdx');
            if (String.isNotBlank(rowIdxStr)) {
                Integer index = Integer.valueOf(rowIdxStr);
                ProductRow currentRow = rows[index - 1];
                if (String.isNotBlank(currentRow.productName)) {
                    List<MICC_Product__c> master = [SELECT Id, Name, Product_Type__c, Product_Indication_Medicus__c FROM MICC_Product__c WHERE Name = :currentRow.productName LIMIT 1];
                    if (!master.isEmpty()) {
                        currentRow.productObj.MICC_Product_Link__c = master[0].Id;
                        currentRow.productType = master[0].Product_Type__c;
                        currentRow.indication = master[0].Product_Indication_Medicus__c;
                    }
                }
            }
        } catch (Exception e) { System.debug('Auto-fetch failed: ' + e.getMessage()); }
    }
    
    public void addRow() { if (rows.size() < 10) rows.add(new ProductRow(rows.size() + 1)); }
    public Integer rowToRemoveIndex {get; set;}
    public void removeRow() {
        if (rows.size() > 1) {
            for (Integer i = 0; i < rows.size(); i++) {
                if (rows[i].srNo == rowToRemoveIndex) { rows.remove(i); break; }
            }
            for (Integer i = 0; i < rows.size(); i++) rows[i].srNo = i + 1;
        }
    }
    
    public void addAERow() { if (aeRows.size() < 10) aeRows.add(new AERow(aeRows.size() + 1)); }
    public Integer aeRowToRemoveIndex {get; set;}
    public void removeAERow() {
        if (aeRows.size() > 1) {
            for (Integer i = 0; i < aeRows.size(); i++) {
                if (aeRows[i].aeNo == aeRowToRemoveIndex) { aeRows.remove(i); break; }
            }
            for (Integer i = 0; i < aeRows.size(); i++) aeRows[i].aeNo = i + 1;
        }
    }
    
    public void toggleAETable() {}
    
    public class ProductRow {
        public Integer srNo {get; set;}
        public String productName {get; set;}
        public String productType {get; set;}
        public String indication {get; set;}
        public String dose {get; set;}
        public String frequency {get; set;}
        public String route {get; set;}
        public String lotNumber {get; set;}
        public Date expiryDate {get; set;}
        public Date therapyStartDate {get; set;}
        public Date therapyEndDate {get; set;}
        public String pickupStatus {get; set;}
        public String technicalComplaint {get; set;}
        public String technicalComplaintNumber {get; set;}
        public String technicalComplaintDescription {get; set;}
        public New_Potential_Adverse_Event__c productObj {get; set;}
        public ProductRow(Integer srNo) {
            this.srNo = srNo; this.productName = ''; this.productType = ''; this.indication = '';
            this.pickupStatus = 'Unknown'; this.technicalComplaint = 'Unknown';
            this.productObj = new New_Potential_Adverse_Event__c();
        }
    }
    
    public class AERow {
        public Integer aeNo {get; set;}
        public String eventName {get; set;}
        public Date startDate {get; set;}
        public Date endDate {get; set;}
        public String outcome {get; set;}
        public AERow(Integer no) { this.aeNo = no; this.eventName = ''; this.outcome = 'Unknown'; }
    }

    public Integer selectedRowIndex {get; set;}
    public ProductRow selectedRow {get; set;}
    public void showDetails() {
        if (selectedRowIndex != null && selectedRowIndex > 0 && selectedRowIndex <= rows.size()) {
            selectedRow = rows[selectedRowIndex - 1];
        }
    }
    public void saveDetails() {}
    
    public PageReference saveAllData() {
        try {
            mainAE.Death__c = seriousnessDeath;
            mainAE.Life_Threatening__c = seriousnessLifeThreatening;
            mainAE.Disability__c = seriousnessDisability;
            mainAE.Hospitalization__c = seriousnessHospitalization;
            mainAE.Congenital_Anomaly__c = seriousnessCongenitalAnomaly;
            mainAE.Other_Seriousness__c = seriousnessOther;
            mainAE.Event_Description__c = eventDescription;
            mainAE.Relevant_Medical_History__c = relevantMedicalHistory;

            if(!rows.isEmpty()) {
                // Mirror first row to parent for convenience
                ProductRow r = rows[0];
                mainAE.Product_Name__c = r.productName;
                mainAE.Product_Type__c = r.productType;
                mainAE.Product_Indication__c = r.indication;
                mainAE.Dose__c = r.dose;
                mainAE.Frequency__c = r.frequency;
                mainAE.Route_of_administering__c = r.route;
                mainAE.Lot_Number__c = r.lotNumber;
                mainAE.Expiry_Date__c = r.expiryDate;
                mainAE.Therapy_Start_Date__c = r.therapyStartDate;
                mainAE.Therapy_End_Date__c = r.therapyEndDate;
                mainAE.Pickup_Status__c = r.pickupStatus;
                mainAE.Is_Technical_Complaint__c = r.technicalComplaint;
                mainAE.Technical_Complaint_Desc__c = r.technicalComplaintDescription;
                mainAE.Technical_Complaint_Number__c = r.technicalComplaintNumber;
                mainAE.MICC_Product_Link__c = r.productObj.MICC_Product_Link__c;
            }
            insert mainAE;
            
            // Save Multiple Products
            List<AE_Product__c> productRecords = new List<AE_Product__c>();
            for(ProductRow pr : rows) {
                if(String.isNotBlank(pr.productName) || pr.productObj.MICC_Product_Link__c != null) {
                    AE_Product__c childProd = new AE_Product__c();
                    childProd.New_Potential_Adverse_Event__c = mainAE.Id;
                    childProd.Name = String.isNotBlank(pr.productName) ? pr.productName : 'Product';
                    childProd.Dose__c = pr.dose;
                    childProd.Frequency__c = pr.frequency;
                    childProd.Route_of_administering__c = pr.route;
                    childProd.Lot_Number__c = pr.lotNumber;
                    childProd.Expiry_Date__c = pr.expiryDate;
                    childProd.Therapy_Start_Date__c = pr.therapyStartDate;
                    childProd.Therapy_End_Date__c = pr.therapyEndDate;
                    childProd.Product_pickup_availability_status_is__c = pr.pickupStatus;
                    childProd.Is_this_a_technical_complaint__c = pr.technicalComplaint;
                    childProd.Technical_complaint__c = pr.technicalComplaintDescription;
                    productRecords.add(childProd);
                }
            }
            if(!productRecords.isEmpty()) insert productRecords;
            
            // Save Individual Adverse Events
            if (addIndividualEventsFlag && !aeRows.isEmpty()) {
                List<AE_Individual_Event__c> childEvents = new List<AE_Individual_Event__c>();
                for (AERow ae : aeRows) {
                    if (String.isNotBlank(ae.eventName)) {
                        AE_Individual_Event__c child = new AE_Individual_Event__c();
                        child.New_Potential_Adverse_Event__c = mainAE.Id;
                        child.Name = ae.eventName;
                        child.AE_Start_Date__c = ae.startDate;
                        child.AE_End_Date__c = ae.endDate;
                        child.Outcome__c = ae.outcome;
                        childEvents.add(child);
                    }
                }
                if (!childEvents.isEmpty()) insert childEvents;
            }
            
            return new PageReference('/' + mainAE.Id);
        } catch (Exception e) { ApexPages.addMessages(e); return null; }
    }
}